const SPRITE_DIR = "/animations/Individual Sprites";

const SPRITE_FILES = [
    "adventurer-crouch-walk-00.png",
    "adventurer-crouch-walk-01.png",
    "adventurer-crouch-walk-02.png",
    "adventurer-crouch-walk-03.png",
    "adventurer-crouch-walk-04.png",
    "adventurer-crouch-walk-05.png",
    "adventurer-drop-kick-00.png",
    "adventurer-drop-kick-01.png",
    "adventurer-drop-kick-02.png",
    "adventurer-drop-kick-03.png",
    "adventurer-get-up-00.png",
    "adventurer-get-up-01.png",
    "adventurer-get-up-02.png",
    "adventurer-get-up-03.png",
    "adventurer-get-up-04.png",
    "adventurer-get-up-05.png",
    "adventurer-get-up-06.png",
    "adventurer-kick-00.png",
    "adventurer-kick-01.png",
    "adventurer-kick-02.png",
    "adventurer-kick-03.png",
    "adventurer-kick-04.png",
    "adventurer-kick-05.png",
    "adventurer-kick-06.png",
    "adventurer-kick-07.png",
    "adventurer-knock-dwn-00.png",
    "adventurer-knock-dwn-01.png",
    "adventurer-knock-dwn-02.png",
    "adventurer-knock-dwn-03.png",
    "adventurer-knock-dwn-04.png",
    "adventurer-knock-dwn-05.png",
    "adventurer-knock-dwn-06.png",
    "adventurer-punch-00.png",
    "adventurer-punch-01.png",
    "adventurer-punch-02.png",
    "adventurer-punch-03.png",
    "adventurer-punch-04.png",
    "adventurer-punch-05.png",
    "adventurer-punch-06.png",
    "adventurer-punch-07.png",
    "adventurer-punch-08.png",
    "adventurer-punch-09.png",
    "adventurer-punch-10.png",
    "adventurer-punch-11.png",
    "adventurer-punch-12.png",
    "adventurer-run2-00.png",
    "adventurer-run2-01.png",
    "adventurer-run2-02.png",
    "adventurer-run2-03.png",
    "adventurer-run2-04.png",
    "adventurer-run2-05.png",
    "adventurer-run-punch-00.png",
    "adventurer-run-punch-01.png",
    "adventurer-run-punch-02.png",
    "adventurer-run-punch-03.png",
    "adventurer-run-punch-04.png",
    "adventurer-run-punch-05.png",
    "adventurer-run-punch-06.png",
    "adventurer-walk-00.png",
    "adventurer-walk-01.png",
    "adventurer-walk-02.png",
    "adventurer-walk-03.png",
    "adventurer-walk-04.png",
    "adventurer-walk-05.png",
    "adventurer-wall-run-00.png",
    "adventurer-wall-run-01.png",
    "adventurer-wall-run-02.png",
    "adventurer-wall-run-03.png",
    "adventurer-wall-run-04.png",
    "adventurer-wall-run-05.png",
] as const;

export const INDIVIDUAL_SPRITE_FRAMES = SPRITE_FILES.map(
    (file) => `${SPRITE_DIR}/${file}`
);
